before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY



build_image:
    tags:
        - docker
    stage: build
    script:
        - docker build -t $CI_REGISTRY/moritzreich/nuxt-build-image:$CI_COMMIT_REF_NAME .
        - docker tag $CI_REGISTRY/moritzreich/nuxt-build-image:$CI_COMMIT_REF_NAME $CI_REGISTRY/moritzreich/nuxt-build-image:latest
        - docker push $CI_REGISTRY/moritzreich/nuxt-build-image:$CI_COMMIT_REF_NAME
workflow:
    rules:
        - if: $CI_COMMIT_TAG